export interface AdditionalWorksRequest {
    id?: number,
    usuarioCreacion?: string,
    terminalCreacion?: string,
    usuarioModificacion?: string,
    terminalModificacion?: string,
    getsW?: number,
    idObjeto: number,
    c55Codigo?: string,
    c56Descripcion?: string,
    c57FechaMes?: string,
    c57FechaAnio?: string,
    c57FechaConstruccion?: Date,
    c58Mep?: string,
    c58IdMep?: number,
    c59Ecs?: string,
    c59IdEcs?: number,
    c60Ecc?: string,
    c60IdEcc?: number,
    c61ProductoTotal?: string,
    c62UnidadMedida?: string,
    c62IdUnidadMedida?: number,
    c63Uca?: string,
    c63IdUca?: number
}