export interface BienesComunesResponse {
    codigoDepartamento?: string,
    codigoDistrito?: string,
    codigoEdificacion?: number,
    codigoEstado?: string,
    nombreEstado?: string,
    codigoProvincia?: string,
    codigoSector?: string,
    codigoManzana?: string,
    codigoLote?: string,
    codigoBienComun?: number,
    entrada?: string,
    numeroPiso?: string,
    numeroEdificacion?: string,
    numeroUnidadAdministrativa?: string,
    terminalCreacion?: string,
    terminalModificacion?: string,    
    usuarioCreacion?: string,    
    usuarioModificacion?: string
}