export interface UnidadAdministrativaResponse {
    codigoDepartamento?: string,
    codigoDistrito?: string,
    codigoEdificacion?: number,
    codigoEstado?: string,
    codigoProvincia?: string,
    codigoSector?: string,
    codigoTipoInterior?: string,
    nombreTipoInterior?: string,
    codigoUnidadAdministrativa: number,
    codigoVia?: string,
    codigoViaLote?: number,
    entrada?: string,
    loteUrbano?: string,
    manzanaUrbana?: string,
    nombreVia?: string,
    numeroEdificacion?: string,    
    numeroInterior?: string,
    numeroPiso?: string,
    numeroUnidadAdministrativa?: string,
    terminalCreacion?: string,
    terminalModificacion?: string,    
    usuarioCreacion?: string,    
    usuarioModificacion?: string
}